# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1:
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    layout:
      showDarkRightPanel: true
    colors:
      primary:
        main: "#222222"
    logo:
      gutter: "20px"
    fab:
      color: "#FFFFFF"
      backgroundColor: "#111111"
    rightPanel:
      backgroundColor: "#222222"
      panelBackgroundColor: "#000000"
      panelControlsBackgroundColor: "#111111"
    shape:
      borderRadius: "0px"
    typography:
      fontFamily: "AkkuratLLWeb-Regular"
      code:
        fontFamily: "AkkuratMonoLLWeb-Regular"
      headings:
        fontFamily: "AkkuratMonoLLWeb-Regular"
        fontWeight: "100"
  generateCodeSamples:
    languages: # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
